### ISSUE TITLE
Creación de models a través de Json

### ISSUE THREAD

**Issue by mangorex** [Proyecto-EGC-G1/CabinaVotaciones-EGC-G1#20]
Investigacion y creación de modelos de datos a traves del JSON recibido por otros subsistemas.

Se hará uso de APIS:
- GET a administracion de votaciones para sacar el voto
- POST a almacenamiento para enviarlo

**Comment by earthtofran** [comment]
Finalmente no se accederá a los datos mediante API. Se accederá a la base de datos compartida.
