### ISSUE TITLE
Integración del proyecto en un Docker junto a todo lo necesario

### ISSUE THREAD

**Issue by mangorex** [Proyecto-EGC-G1/CabinaVotaciones-EGC-G1#40]
Introducir el proyecto en un Docker, junto con todo lo necesario para la ejecución del mismo.
Este docker debe de conectarse junto al docker, que aportó integración, que contiene la base de datos MariaDB que se va a usar.

**Comment by mangorex** [comment]
Este issue ha sido comenzado. Se investigará si meter en el docker lo necesario para desplegar con un WAR y Apache Tomcat u otra tecnología

**Comment by earthtofran** [comment]
Este issue esta dubplicado y se hace referencia en: #85
