### ISSUE TITLE
Modificar la clase OptionPerVote en BD

### ISSUE THREAD

**Issue by ArturoRonda** [Proyecto-EGC-G1/CabinaVotaciones-EGC-G1#42]
Desde recuento de votos necesitamos implementar un nuevo campo integer dentro de la clase OptionPerVote.

El nuevo campo permite hacer un recuento teniendo en cuenta el orden de las posibles respuestas, podría ser 0 no null,  el valor vendría dado por la preferencia que de el votante a cada respuesta.

Desde integración nos han solicitado vuestra confirmación.

**Comment by earthtofran** [comment]
Nos parece correcta la propuesta. En la reunión de coordinación del día 14 de diciembre se podrá discutir y acordar este tema.
